### ISSUE TITLE
reproducibility attempts (on mac mini)

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/solomon-analysis#4]
## Attempt 1 (documented in https://github.com/LAAC-LSCP/solomon-analysis/tree/reprod-chk)

- cloned this repo
- created a branch reprod-chk
- wrote what I did in the README, which was basically:
- installed dataset with datalad
- got the annotations
- then tried to launch vc.py
- that gave me an error as if it was not finding the children metadata
- even though the data were there
- LG said it may give that error bc audiofiles were missing & recommended pull & try again
- I git-pulled the data - same error
- I switched to the main branch & git-pulled the code
- I launched vc.py again as instructed and got no message whatsoever
- I removed the all_stats.csv from output and tried again
- no error, but all_stats.csv is not created

## Attempt 2 

I figured I must have gone wrong from the start, so I wanted to delete my copies of the data & start over following LG's instructions.

- I did rm -rf solomon-data
- got errors like "rm: solomon-data//.git: Directory not empty" and "rm: solomon-data/: Directory not empty" and "rm: solomon-data//.git/annex/objects/25/J1/MD5E-s462--1067a53936a8f64294518e99c0d5c5b8.csv/MD5E-s462--1067a53936a8f64294518e99c0d5c5b8.csv: Permission denied" but the folder disappeared

`$ datalad install git@github.com:LAAC-LSCP/solomon-data.git`
> [ERROR  ] target path already exists and not empty, refuse to clone into target path [install(/Users/acristia/Documents/gitrepos/solomon-data)] 
install(error): /Users/acristia/Documents/gitrepos/solomon-data (dataset) [target path already exists and not empty, refuse to clone into target path]

`$ datalad uninstall solomon-data` 
> [ERROR  ] No dataset found at '/Users/acristia/Documents/gitrepos'.  Specify a dataset to work with by providing its path via the `dataset` option, or change the current working directory to be in a dataset. [dataset.py:require_dataset:573] (NoDatasetFound) 

`$ datalad uninstall -d /Users/acristia/Documents/gitrepos/solomon-data/`
> [ERROR  ] No installed dataset found at /Users/acristia/Documents/gitrepos/solomon-data. [dataset.py:require_dataset:583] (ValueError) 

## Attempt 3: clean slate (SUCCESS)

- I created a new folder, and tried to install the dataset in there

`$ datalad install git@github.com:LAAC-LSCP/solomon-data.git`
> Clone attempt:   0%|                                                                                                                               | 0.00/1.00 [00:00<?, ? Candidate locations/s]Warning: Permanently added the RSA host key for IP address '140.82.121.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
[ERROR  ] Failed to clone from all attempted sources: ['git@github.com:LAAC-LSCP/solomon-data.git'] [install(/Users/acristia/Documents/gitrepos/solomon/solomon-data)]                           
install(error): /Users/acristia/Documents/gitrepos/solomon/solomon-data (dataset) [Failed to clone from all attempted sources: ['git@github.com:LAAC-LSCP/solomon-data.git']]

`$ datalad install https://github.com/LAAC-LSCP/solomon-data` worked, proceeding with subsequent steps

With this new install, I could reproduce the analyses.

**Comment by lucasgautheron** [comment]
I've written instructions just today, here they are : https://github.com/LAAC-LSCP/solomon-analysis/blob/main/README.md

When you do `datalad install git@github.com:LAAC-LSCP/solomon-data.git`, you are cloning the github repository over ssh, which will only work if you have configured your ssh key on github. You might want to use https instead, as we've discussed last time - since it seems to be the way you're interacting with github usually.

The instructions in the README show how to do it over https. But really it is up to the user to choose between https or ssh (I use ssh)

Regarding the  issue with the missing table you encountered, I found it was because of bash expanding rules for ~ 
Python does expand the paths itself. ([explanations](https://askubuntu.com/questions/890415/why-couldnt-i-use-instead-of-home-username-when-giving-the-file-pat) here)
